---
- name: nginx
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - nginx

    - name: stop nginx
      service: name=nginx state=stopped