---
- name: nginx
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - nginx

    - name: Add user "nginx"
      user:
        name: nginx
        shell: /sbin/nologin
        append: yes
        comment: "nginx nologin User"
        state: present

    - name: stop nginx
      service: name=nginx state=stopped
