name: Packer

on:
  push:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Packer init
        run: packer init base/
      - name: Packer validate
        run: packer validate -syntax-only base/
      - name: Packer build base
        run: |
          packer build -color=false -on-error=abort base/

      - name: Packer init
        run: packer init .
      - name: Packer validate
        run: packer validate -syntax-only .
      - name: Packer build base
        run: |
          packer build -color=false -on-error=abort .
